-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.dept_emp DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.dept_manager DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.dept_manager DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.dept_manager DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public.employees DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public.department;

CREATE TABLE IF NOT EXISTS public.department
(
    dept_no character varying NOT NULL,
    dept_name character varying NOT NULL,
    PRIMARY KEY (dept_no)
);

DROP TABLE IF EXISTS public.dept_emp;

CREATE TABLE IF NOT EXISTS public.dept_emp
(
    emp_no integer NOT NULL,
    dept_no character varying NOT NULL
);

DROP TABLE IF EXISTS public.dept_manager;

CREATE TABLE IF NOT EXISTS public.dept_manager
(
    dept_no character varying NOT NULL,
    emp_no integer NOT NULL,
    PRIMARY KEY (dept_no, emp_no)
);

DROP TABLE IF EXISTS public.employees;

CREATE TABLE IF NOT EXISTS public.employees
(
    emp_no integer NOT NULL,
    emp_title character varying NOT NULL,
    birth_date date NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    sex character varying NOT NULL,
    hire_date date NOT NULL,
    PRIMARY KEY (emp_no)
);

DROP TABLE IF EXISTS public.salaries;

CREATE TABLE IF NOT EXISTS public.salaries
(
    emp_no integer NOT NULL,
    salary integer NOT NULL,
    PRIMARY KEY (emp_no)
);

DROP TABLE IF EXISTS public.titles;

CREATE TABLE IF NOT EXISTS public.titles
(
    title_id character varying NOT NULL,
    title character varying NOT NULL
);

ALTER TABLE IF EXISTS public.dept_emp
    ADD FOREIGN KEY (dept_no)
    REFERENCES public.department (dept_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_manager
    ADD FOREIGN KEY (dept_no)
    REFERENCES public.department (dept_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_manager
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.salaries (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.dept_manager
    ADD FOREIGN KEY (emp_no)
    REFERENCES public.employees (emp_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employees
    ADD FOREIGN KEY (emp_title)
    REFERENCES public.titles (title_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;